### ISSUE TITLE
Sorry 

### ISSUE THREAD

**Issue by SebLanzar8** [Yogu/curvy#2]
I have a mentally unstable friend, which sometime can't control his action, is like a tourette guy without being touretted.
He manage somehow to broke the heroku server, but me and anothere friend of mine was really having great time with your game and we will love to have again the fun that your game was giving.
Can you kindly bring the service up again ?
I promise that we are gonna take our friend away from you chat system:):)
 Thanks for your time... 
ah... the ball sometime still get red:(

**Comment by Yogu** [comment]
Ah no worries, you did not break it. It's just that heroku no longer offers their "free tier" which was used by curvy. I'll see if I find a different way to set up the server.

Great to hear that you are still enjoying the game :)

**Comment by SebLanzar8** [comment]
Thanks a lot
